/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package liarsdice;
import java.awt.Color;
import java.awt.Font;
import java.io.*;
import java.util.*;
import java.util.Random;
import javax.swing.JRadioButton;

/**
 *
 * @author Computer
 */
public class LiarsDiceJframe extends javax.swing.JFrame {

    gameState state;
    /**
     * Creates new form LiarsDiceJframe
     */
    public LiarsDiceJframe() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        testlabel = new javax.swing.JLabel();
        cpuContainer = new javax.swing.JPanel();
        cpuPanel1 = new javax.swing.JPanel();
        cpuCup1 = new javax.swing.JLabel();
        cpuPanel2 = new javax.swing.JPanel();
        cpuCup2 = new javax.swing.JLabel();
        cpuPanel3 = new javax.swing.JPanel();
        cpuCup3 = new javax.swing.JLabel();
        playerDicePanel = new javax.swing.JPanel();
        die1 = new javax.swing.JLabel();
        die2 = new javax.swing.JLabel();
        die3 = new javax.swing.JLabel();
        die4 = new javax.swing.JLabel();
        die5 = new javax.swing.JLabel();
        playerControlPanel = new javax.swing.JPanel();
        radio2 = new javax.swing.JRadioButton();
        radio3 = new javax.swing.JRadioButton();
        radio4 = new javax.swing.JRadioButton();
        radio5 = new javax.swing.JRadioButton();
        radio6 = new javax.swing.JRadioButton();
        betSlider = new javax.swing.JSlider();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Liar's Dice");
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.Y_AXIS));

        testlabel.setText("Liars Dice");
        getContentPane().add(testlabel);

        cpuContainer.setLayout(new java.awt.BorderLayout());

        cpuPanel1.setLayout(new javax.swing.BoxLayout(cpuPanel1, javax.swing.BoxLayout.X_AXIS));

        cpuCup1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/5cup.png"))); // NOI18N
        cpuPanel1.add(cpuCup1);

        cpuContainer.add(cpuPanel1, java.awt.BorderLayout.WEST);

        cpuPanel2.setLayout(new javax.swing.BoxLayout(cpuPanel2, javax.swing.BoxLayout.Y_AXIS));

        cpuCup2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/5cup.png"))); // NOI18N
        cpuCup2.setAlignmentX(0.5F);
        cpuPanel2.add(cpuCup2);

        cpuContainer.add(cpuPanel2, java.awt.BorderLayout.NORTH);

        cpuPanel3.setLayout(new javax.swing.BoxLayout(cpuPanel3, javax.swing.BoxLayout.X_AXIS));

        cpuCup3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/5cup.png"))); // NOI18N
        cpuPanel3.add(cpuCup3);

        cpuContainer.add(cpuPanel3, java.awt.BorderLayout.EAST);

        getContentPane().add(cpuContainer);

        playerDicePanel.setLayout(new javax.swing.BoxLayout(playerDicePanel, javax.swing.BoxLayout.LINE_AXIS));

        die1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/d2.png"))); // NOI18N
        die1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        playerDicePanel.add(die1);

        die2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/d2.png"))); // NOI18N
        die2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        playerDicePanel.add(die2);

        die3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/d2.png"))); // NOI18N
        die3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        playerDicePanel.add(die3);

        die4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/d2.png"))); // NOI18N
        die4.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        playerDicePanel.add(die4);

        die5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/d2.png"))); // NOI18N
        die5.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        playerDicePanel.add(die5);

        getContentPane().add(playerDicePanel);

        buttonGroup1.add(radio2);
        radio2.setText("Two's");

        buttonGroup1.add(radio3);
        radio3.setText("Three's");

        buttonGroup1.add(radio4);
        radio4.setText("Four's");

        buttonGroup1.add(radio5);
        radio5.setText("Five's");
        radio5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radio5ActionPerformed(evt);
            }
        });

        buttonGroup1.add(radio6);
        radio6.setText("Six's");

        betSlider.setMajorTickSpacing(5);
        betSlider.setMaximum(20);
        betSlider.setMinorTickSpacing(1);
        betSlider.setPaintLabels(true);
        betSlider.setPaintTicks(true);
        betSlider.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                betSliderStateChanged(evt);
            }
        });

        jButton2.setText("Call Lie");

        jButton1.setText("Make Bet");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout playerControlPanelLayout = new javax.swing.GroupLayout(playerControlPanel);
        playerControlPanel.setLayout(playerControlPanelLayout);
        playerControlPanelLayout.setHorizontalGroup(
            playerControlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(playerControlPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(playerControlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(playerControlPanelLayout.createSequentialGroup()
                        .addComponent(radio2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(radio3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(radio4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(radio5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(radio6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(betSlider, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(playerControlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        playerControlPanelLayout.setVerticalGroup(
            playerControlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, playerControlPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(playerControlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radio2)
                    .addComponent(radio3)
                    .addComponent(radio4)
                    .addComponent(radio5)
                    .addComponent(radio6)
                    .addComponent(jButton2))
                .addGap(18, 18, 18)
                .addGroup(playerControlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(betSlider, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        getContentPane().add(playerControlPanel);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    public void setState(gameState a){
        state = a;
    }
    
    public void updateBetLimits(int count, int value){
        betSlider.setMinimum(count);
    }
        
    public javax.swing.ImageIcon rollDie(){
        ArrayList<String> images = new ArrayList<String>(
        Arrays.asList("/d1.png", "/d2.png", "/d3.png", "/d4.png", "/d5.png", "/d6.png"));
        
        
                    
        Random gen = new Random();
        int dval = gen.nextInt(6);
        return(new javax.swing.ImageIcon(getClass().getResource(images.get(dval))));
    }
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        ArrayList<javax.swing.JLabel> dice = new ArrayList<>(
            Arrays.asList(die1, die2, die3, die4, die5));
        ArrayList<javax.swing.JRadioButton> radioButtons = new ArrayList<>(
            Arrays.asList(radio2,radio3,radio4,radio5,radio6));
        
        Font clickmeFont=new Font("Tahoma",Font.BOLD,radio2.getFont().getSize());
        Font defaultFont=new Font("Tahoma",Font.PLAIN,11);
        
        for (javax.swing.JLabel die : dice){
            die.setIcon(rollDie());
        }
        
        int betValue = dataConverter.getCountFromButton(buttonGroup1);
        
        if (betValue == 0){
            for(JRadioButton b : radioButtons){
                b.setFont(clickmeFont);
                b.setForeground(Color.red);
            }
        }
        
        else{
            int betCount = betSlider.getValue();
            
            System.out.println("total dice: " +state.getDice());
            System.out.println("betCount: " +betCount);
            System.out.println("betValue: " +betValue);

            state.updateBet(betCount, betValue);
            updateBetLimits(betCount, betValue);
            for(JRadioButton b : radioButtons){
                b.setFont(defaultFont);
                b.setForeground(Color.black);
            }
        }
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void radio5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radio5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radio5ActionPerformed

    private void betSliderStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_betSliderStateChanged
        
        int value = betSlider.getValue();
        ArrayList<javax.swing.JRadioButton> radioButtons = new ArrayList<>(
        Arrays.asList(radio2,radio3,radio4,radio5,radio6));
        if (state.getBetCount() == value){
            
            int i=2;
            for (javax.swing.JRadioButton button : radioButtons){
                if (i <= state.getBetValue()){
                    button.getModel().setEnabled(false);
                    buttonGroup1.clearSelection();
                }
                else{
                    button.getModel().setEnabled(true);
                }
                i++;
            }
        }
        else{
            for (javax.swing.JRadioButton button : radioButtons){
                 button.getModel().setEnabled(true);
            }
        }
    }//GEN-LAST:event_betSliderStateChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSlider betSlider;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JPanel cpuContainer;
    private javax.swing.JLabel cpuCup1;
    private javax.swing.JLabel cpuCup2;
    private javax.swing.JLabel cpuCup3;
    private javax.swing.JPanel cpuPanel1;
    private javax.swing.JPanel cpuPanel2;
    private javax.swing.JPanel cpuPanel3;
    private javax.swing.JLabel die1;
    private javax.swing.JLabel die2;
    private javax.swing.JLabel die3;
    private javax.swing.JLabel die4;
    private javax.swing.JLabel die5;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JPanel playerControlPanel;
    private javax.swing.JPanel playerDicePanel;
    private javax.swing.JRadioButton radio2;
    private javax.swing.JRadioButton radio3;
    private javax.swing.JRadioButton radio4;
    private javax.swing.JRadioButton radio5;
    private javax.swing.JRadioButton radio6;
    private javax.swing.JLabel testlabel;
    // End of variables declaration//GEN-END:variables
}
